version: '3.8'
services:
  gtbank-whatsapp-api:
    image: pkasemer/gtbank-whatsapp-api:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ./generated:/usr/src/app/src/public/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
