version: '3.8'
services:
  gtbank-whatsapp-api:
    image: pkasemer/gtbank-whatsapp-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - LOG_DIR=/app/logs
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
